title: PowerShell Tools for Visual Studio
description: PowerShell integration for Visual Studio 2012 and 2013.
google_analytics: 
show_downloads: true
theme: jekyll-theme-time-machine

gems:
  - jekyll-mentions
